version: "2.2"
services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - ORACLE_URL=${ORACLE_URL}
    volumes:
      - ./app:/app
